name = "selfsign-job.<%=namespace%>"
image = "arobson/k8s-certbot"
command = "selfsign"
job = true

[env]
  CERT_ETCD_NAMESPACE = "<%= keyspace %>"
  CERT_ECTD_URL = "<%= etcd %>"
  CERT_DOMAINS = "<%= domains %>"
  CERT_BASE_DOMAIN = "<%= zone %>"
  CERT_EMAIL = "<%= email %>"
  CERT_COUNTRY = "<%= country %>"
  CERT_STATE = "<%= state %>"
  CERT_LOCAL = "<%= local %>"
  CERT_ORG = "<%= organization %>"
  CERT_UNIT = "<%= unit %>"
